datasets:
  raw:
    google:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/Data/google_search_data.csv
      driver_params: {}
  
    product:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/Data/product_manufacturer_list.csv
      driver_params: {}

    sales:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/Data/sales_data.csv
      driver_params: {}
    
    media:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/Data/social_media_data.csv
      driver_params: {}

    theme_list:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/Data/Theme_list.csv
      driver_params: {}
    
    tpl:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/Data/Theme_product_list.csv
      driver_params: {}
  
  cleaned:
    google:
      type: ds
      format: csv
      uri: ${core.data_base_path}/cleaned/Data/google_search_data.parquet
      driver_params: {}
  
    product:
      type: ds
      format: csv
      uri: ${core.data_base_path}/cleaned/Data/product_manufacturer_list.parquet
      driver_params: {}

    sales:
      type: ds
      format: csv
      uri: ${core.data_base_path}/cleaned/Data/sales_data.parquet
      driver_params: {}
    
    media:
      type: ds
      format: csv
      uri: ${core.data_base_path}/cleaned/Data/social_media_data.parquet
      driver_params: {}

    theme_list:
      type: ds
      format: csv
      uri: ${core.data_base_path}/cleaned/Data/Theme_list.parquet
      driver_params: {}
    
    tpl:
      type: ds
      format: csv
      uri: ${core.data_base_path}/cleaned/Data/Theme_product_list.parquet
      driver_params: {}

  processed:
    sales:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/processed/Data/sales.parquet
      driver_params: {}

  train:
    sales:
      features:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/train/Data/features.parquet
        driver_params:
          save:
            index: False
      target:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/train/Data/target.parquet
        driver_params:
          save:
            index: False
  test:
    sales:
      features:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/test/Data/features.parquet
        driver_params:
          save:
            index: False
      target:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/test/Data/target.parquet
        driver_params:
          save:
            index: False
  score:
    sales:
      output:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/test/Data/scored_output.parquet
        driver_params:
          save:
            index: False
            